#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from gui/ui/raw.qrc on Mon Oct 22 15:18:28 2012
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
